# Generated by Django 2.2 on 2019-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
